title: "Village Frontier"
description: "The Frontier Lodge — A DayZ Survival Network"
theme: null

include:
  - assets/css/style.css

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
